### ISSUE TITLE
Fix tests and clippy warnings

### ISSUE THREAD

**Issue by juangirini** [ideal-lab5/idn-sdk#64]
Several tests are failing in different parts of the repo, as well as clippy warnings. They should be fixed.
```bash
cargo clippy -- -D warnings
cargo test
```

Then these lines should be added to the `.github/workflow/rust.yml` file
```yaml
    - name: Run cargo clippy
      run: cargo clippy -- -D warnings

    - name: Run cargo test
      run: cargo test --verbose
```
